"""Add address fields

Revision ID: cd09f940837b
Revises: 
Create Date: 2025-12-08 11:46:48.896950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd09f940837b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('uf', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.drop_column('endereco')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('uf')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cep')
    # ### end Alembic commands ###
